import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx,vue,svelte}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				'surface-container-highest': '#e5e2e1',
				outline: '#82727e',
				'secondary-container': '#fdb4f7',
				'on-primary-fixed-variant': '#752177',
				'tertiary-container': '#69646b',
				'surface-dim': '#dcd9d9',
				'on-surface': '#1c1b1b',
				'on-secondary-fixed-variant': '#6a316a',
				'on-tertiary-fixed': '#1e1a20',
				secondary: '#844883',
				'tertiary-fixed': '#e8e0e8',
				'primary-fixed': '#ffd6f8',
				primary: '#7d297f',
				'on-secondary': '#ffffff',
				'tertiary-fixed-dim': '#cbc4cc',
				'on-surface-variant': '#50434e',
				'inverse-primary': '#ffaaf9',
				surface: '#fcf9f8',
				'surface-variant': '#e5e2e1',
				'on-secondary-container': '#7b407a',
				'outline-variant': '#d4c1cf',
				'surface-container-lowest': '#ffffff',
				'on-tertiary': '#ffffff',
				'on-primary-container': '#ffd8f8',
				'primary-fixed-dim': '#ffaaf9',
				'on-error': '#ffffff',
				'surface-bright': '#fcf9f8',
				'secondary-fixed': '#ffd6f8',
				'surface-container-high': '#eae7e7',
				'on-secondary-fixed': '#37003b',
				'on-tertiary-container': '#eae2ea',
				'on-error-container': '#93000a',
				'on-background': '#1c1b1b',
				'surface-tint': '#913c91',
				'secondary-fixed-dim': '#f7aff1',
				'inverse-surface': '#313030',
				'inverse-on-surface': '#f3f0ef',
				background: '#fcf9f8',
				'surface-container': '#f0eded',
				tertiary: '#514c53',
				'on-primary-fixed': '#37003a',
				'surface-container-low': '#f6f3f2',
				error: '#ba1a1a',
				'error-container': '#ffdad6',
				'primary-container': '#994399',
				'on-primary': '#ffffff',
				'on-tertiary-fixed-variant': '#4a454c',
			},
			borderRadius: {
				DEFAULT: '0.25rem',
				lg: '0.5rem',
				xl: '0.75rem',
				full: '9999px',
			},
			spacing: {
				gutter: '24px',
				xl: '80px',
				sm: '12px',
				margin: '32px',
				lg: '48px',
				base: '8px',
				xs: '4px',
				md: '24px',
			},
			fontFamily: {
				'headline-lg-mobile': ['Hanken Grotesk'],
				'headline-lg': ['Hanken Grotesk'],
				'headline-xl': ['Hanken Grotesk'],
				'headline-md': ['Hanken Grotesk'],
				'body-lg': ['Inter'],
				'body-md': ['Inter'],
				'label-md': ['Inter'],
				'body-sm': ['Inter'],
			},
			fontSize: {
				'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
				'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
				'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
				'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
				'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
				'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
				'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
				'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
			},
		},
	},
	plugins: [forms, containerQueries],
};
